export const districts: {city:string,lat:string,lng:string,country:string,
    iso2:string, admin_name:string, capital:string,population:string,population_proper:string}[] = [
    {
      "city": "Kampala", 
      "lat": "0.3136", 
      "lng": "32.5811", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kampala", 
      "capital": "primary", 
      "population": "1659600", 
      "population_proper": "1659600"
    }, 
    {
      "city": "Mbale", 
      "lat": "1.0806", 
      "lng": "34.1750", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mbale", 
      "capital": "admin", 
      "population": "402368", 
      "population_proper": "91800"
    }, 
    {
      "city": "Arua", 
      "lat": "3.0300", 
      "lng": "30.9100", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Arua", 
      "capital": "admin", 
      "population": "250000", 
      "population_proper": "59400"
    }, 
    {
      "city": "Tororo", 
      "lat": "0.6928", 
      "lng": "34.1808", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Tororo", 
      "capital": "admin", 
      "population": "150000", 
      "population_proper": "43700"
    }, 
    {
      "city": "Gulu", 
      "lat": "2.7667", 
      "lng": "32.3056", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Gulu", 
      "capital": "admin", 
      "population": "146858", 
      "population_proper": "142003"
    }, 
    {
      "city": "Lira", 
      "lat": "2.2489", 
      "lng": "32.9000", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Lira", 
      "capital": "admin", 
      "population": "135445", 
      "population_proper": "119323"
    }, 
    {
      "city": "Mbarara", 
      "lat": "-0.5996", 
      "lng": "30.6500", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mbarara", 
      "capital": "admin", 
      "population": "83700", 
      "population_proper": "83700"
    }, 
    {
      "city": "Bombo", 
      "lat": "0.5833", 
      "lng": "32.5333", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Luwero", 
      "capital": "", 
      "population": "75000", 
      "population_proper": "21000"
    }, 
    {
      "city": "Jinja", 
      "lat": "0.4431", 
      "lng": "33.2128", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Jinja", 
      "capital": "admin", 
      "population": "72931", 
      "population_proper": "72931"
    }, 
    {
      "city": "Entebbe", 
      "lat": "0.0500", 
      "lng": "32.4600", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Wakiso", 
      "capital": "", 
      "population": "69958", 
      "population_proper": "69958"
    }, 
    {
      "city": "Kasese", 
      "lat": "0.2300", 
      "lng": "29.9883", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kasese", 
      "capital": "admin", 
      "population": "67269", 
      "population_proper": "67269"
    }, 
    {
      "city": "Masaka", 
      "lat": "-0.3296", 
      "lng": "31.7300", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Masaka", 
      "capital": "admin", 
      "population": "65373", 
      "population_proper": "65373"
    }, 
    {
      "city": "Kitgum", 
      "lat": "3.3004", 
      "lng": "32.8700", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kitgum", 
      "capital": "admin", 
      "population": "56891", 
      "population_proper": "8680"
    }, 
    {
      "city": "Busia", 
      "lat": "0.4669", 
      "lng": "34.0900", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Busia", 
      "capital": "admin", 
      "population": "47100", 
      "population_proper": "47100"
    }, 
    {
      "city": "Iganga", 
      "lat": "0.6092", 
      "lng": "33.4686", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Iganga", 
      "capital": "admin", 
      "population": "45024", 
      "population_proper": "45024"
    }, 
    {
      "city": "Kabale", 
      "lat": "-1.2496", 
      "lng": "29.9800", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kabale", 
      "capital": "admin", 
      "population": "44600", 
      "population_proper": "44600"
    }, 
    {
      "city": "Fort Portal", 
      "lat": "0.6710", 
      "lng": "30.2750", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kabarole", 
      "capital": "admin", 
      "population": "42670", 
      "population_proper": "42670"
    }, 
    {
      "city": "Mityana", 
      "lat": "0.4004", 
      "lng": "32.0500", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mityana", 
      "capital": "admin", 
      "population": "41131", 
      "population_proper": "33710"
    }, 
    {
      "city": "Adjumani", 
      "lat": "3.3614", 
      "lng": "31.8097", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Adjumani", 
      "capital": "admin", 
      "population": "34700", 
      "population_proper": "34700"
    }, 
    {
      "city": "Masindi", 
      "lat": "1.6744", 
      "lng": "31.7150", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Masindi", 
      "capital": "admin", 
      "population": "31486", 
      "population_proper": "31486"
    }, 
    {
      "city": "Pallisa", 
      "lat": "1.1450", 
      "lng": "33.7094", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Pallisa", 
      "capital": "admin", 
      "population": "30745", 
      "population_proper": "30745"
    }, 
    {
      "city": "Nebbi", 
      "lat": "2.4758", 
      "lng": "31.1025", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nebbi", 
      "capital": "admin", 
      "population": "30354", 
      "population_proper": "30354"
    }, 
    {
      "city": "Moyo", 
      "lat": "3.6504", 
      "lng": "31.7200", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Moyo", 
      "capital": "admin", 
      "population": "22434", 
      "population_proper": "22434"
    }, 
    {
      "city": "Kayunga", 
      "lat": "0.7025", 
      "lng": "32.8886", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kayunga", 
      "capital": "admin", 
      "population": "21704", 
      "population_proper": "21704"
    }, 
    {
      "city": "Mubende", 
      "lat": "0.5904", 
      "lng": "31.3700", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mubende", 
      "capital": "admin", 
      "population": "18936", 
      "population_proper": "176"
    }, 
    {
      "city": "Pakwach", 
      "lat": "2.4500", 
      "lng": "31.5000", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nebbi", 
      "capital": "admin", 
      "population": "17541", 
      "population_proper": "17541"
    }, 
    {
      "city": "Ntungamo", 
      "lat": "-0.8794", 
      "lng": "30.2642", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Ntungamo", 
      "capital": "admin", 
      "population": "16400", 
      "population_proper": "16400"
    }, 
    {
      "city": "Kiboga", 
      "lat": "0.9161", 
      "lng": "31.7742", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kiboga", 
      "capital": "admin", 
      "population": "14512", 
      "population_proper": "14512"
    }, 
    {
      "city": "Sironko", 
      "lat": "1.2294", 
      "lng": "34.2481", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Sironko", 
      "capital": "admin", 
      "population": "14100", 
      "population_proper": "14100"
    }, 
    {
      "city": "Kumi", 
      "lat": "1.4608", 
      "lng": "33.9361", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kumi", 
      "capital": "admin", 
      "population": "13000", 
      "population_proper": "13000"
    }, 
    {
      "city": "Kisoro", 
      "lat": "-1.3539", 
      "lng": "29.6983", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kisoro", 
      "capital": "admin", 
      "population": "12900", 
      "population_proper": "12900"
    }, 
    {
      "city": "Kamuli", 
      "lat": "0.9472", 
      "lng": "33.1197", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kamuli", 
      "capital": "admin", 
      "population": "12764", 
      "population_proper": "12764"
    }, 
    {
      "city": "Mpigi", 
      "lat": "0.2250", 
      "lng": "32.3136", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mpigi", 
      "capital": "admin", 
      "population": "11082", 
      "population_proper": "11082"
    }, 
    {
      "city": "Katakwi", 
      "lat": "1.8911", 
      "lng": "33.9661", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Katakwi", 
      "capital": "admin", 
      "population": "8400", 
      "population_proper": "8400"
    }, 
    {
      "city": "Nakasongola", 
      "lat": "1.3089", 
      "lng": "32.4564", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nakasongola", 
      "capital": "admin", 
      "population": "6921", 
      "population_proper": "6921"
    }, 
    {
      "city": "Kalangala", 
      "lat": "-0.3089", 
      "lng": "32.2250", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kalangala", 
      "capital": "admin", 
      "population": "5200", 
      "population_proper": "5200"
    }, 
    {
      "city": "Kaberamaido", 
      "lat": "1.7389", 
      "lng": "33.1594", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kaberamaido", 
      "capital": "admin", 
      "population": "3400", 
      "population_proper": "3400"
    }, 
    {
      "city": "Kaabong", 
      "lat": "3.5204", 
      "lng": "34.1200", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kaabong", 
      "capital": "admin", 
      "population": "1137", 
      "population_proper": "1137"
    }, 
    {
      "city": "Soroti", 
      "lat": "1.6833", 
      "lng": "33.6167", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Soroti", 
      "capital": "admin", 
      "population": "1038", 
      "population_proper": "1038"
    }, 
    {
      "city": "Moroto", 
      "lat": "2.5403", 
      "lng": "34.6400", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Moroto", 
      "capital": "admin", 
      "population": "371", 
      "population_proper": "371"
    }, 
    {
      "city": "Koboko", 
      "lat": "3.4136", 
      "lng": "30.9599", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Koboko", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bugiri", 
      "lat": "0.5714", 
      "lng": "33.7417", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bugiri", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kapchorwa", 
      "lat": "1.3965", 
      "lng": "34.4509", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kapchorwa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bundibugyo", 
      "lat": "0.7085", 
      "lng": "30.0634", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bundibugyo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Hoima", 
      "lat": "1.4356", 
      "lng": "31.3436", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Hoima", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mukono", 
      "lat": "0.3533", 
      "lng": "32.7553", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mukono", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Yumbe", 
      "lat": "3.4651", 
      "lng": "31.2469", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Yumbe", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kasaali", 
      "lat": "-0.6167", 
      "lng": "31.5500", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Rakai", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bududa", 
      "lat": "1.0112", 
      "lng": "34.3311", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bududa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Wakiso", 
      "lat": "0.4044", 
      "lng": "32.4594", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Wakiso", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Lyantonde", 
      "lat": "-0.4031", 
      "lng": "31.1572", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Lyantonde", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mayuge", 
      "lat": "0.4578", 
      "lng": "33.4806", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mayuge", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bulambuli", 
      "lat": "1.1667", 
      "lng": "34.3833", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bulambuli", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Maracha", 
      "lat": "3.2704", 
      "lng": "30.9553", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Maracha", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Luwero", 
      "lat": "0.8492", 
      "lng": "32.4731", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Luwero", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Namayingo", 
      "lat": "0.2398", 
      "lng": "33.8849", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Namayingo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Luuka Town", 
      "lat": "0.7008", 
      "lng": "33.3002", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Luuka", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kibuku", 
      "lat": "1.0433", 
      "lng": "33.7975", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kibuku", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bupoto", 
      "lat": "0.9061", 
      "lng": "34.3578", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Manafwa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Apac", 
      "lat": "1.9845", 
      "lng": "32.5340", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Apac", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rubirizi", 
      "lat": "-0.2989", 
      "lng": "30.1336", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Rubirizi", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Busesa", 
      "lat": "0.6263", 
      "lng": "33.6003", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Iganga", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Buikwe", 
      "lat": "0.3375", 
      "lng": "33.0106", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Buikwe", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kagadi", 
      "lat": "0.9378", 
      "lng": "30.8089", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kibaale", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bushenyi", 
      "lat": "-0.5853", 
      "lng": "30.2114", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Buhweju", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kaliro", 
      "lat": "0.8949", 
      "lng": "33.5048", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kaliro", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Butebo", 
      "lat": "1.1942", 
      "lng": "33.9222", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Pallisa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Namutumba", 
      "lat": "0.8363", 
      "lng": "33.6858", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Namutumba", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Manafwa", 
      "lat": "0.9784", 
      "lng": "34.3743", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Manafwa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ibanda", 
      "lat": "-0.1539", 
      "lng": "30.5319", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Ibanda", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rukungiri", 
      "lat": "-0.8411", 
      "lng": "29.9419", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Rukungiri", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Gombe", 
      "lat": "0.1818", 
      "lng": "32.1158", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Butambala", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kyenjojo", 
      "lat": "0.6328", 
      "lng": "30.6214", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kyenjojo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mitoma", 
      "lat": "-0.6842", 
      "lng": "30.0700", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mitooma", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kalungu", 
      "lat": "-0.1667", 
      "lng": "31.7569", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kalungu", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bukomansimbi", 
      "lat": "-0.1578", 
      "lng": "31.6042", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bukomansimbi", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rubanda", 
      "lat": "-1.1883", 
      "lng": "29.8461", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kabale", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Butaleja", 
      "lat": "0.9166", 
      "lng": "33.9563", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Butaleja", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Serere", 
      "lat": "1.5180", 
      "lng": "33.4589", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Serere", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Amuria", 
      "lat": "2.0036", 
      "lng": "33.6511", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Amuria", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Nsiika", 
      "lat": "-0.3831", 
      "lng": "30.4650", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Buhweju", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kibiito", 
      "lat": "0.4772", 
      "lng": "30.1925", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kabarole", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kibingo", 
      "lat": "-0.6260", 
      "lng": "30.4359", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Sheema", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bukedea", 
      "lat": "1.3169", 
      "lng": "34.0506", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bukedea", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ntara", 
      "lat": "0.0044", 
      "lng": "30.3658", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kamwenge", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Binyin", 
      "lat": "1.4167", 
      "lng": "34.5333", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kween", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mparo", 
      "lat": "-1.1647", 
      "lng": "30.0378", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kabale", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kinoni", 
      "lat": "-0.6583", 
      "lng": "30.4581", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Sheema", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kole", 
      "lat": "2.4002", 
      "lng": "32.8003", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kole", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Zombo", 
      "lat": "2.5135", 
      "lng": "30.9091", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Zombo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rakai", 
      "lat": "-0.7200", 
      "lng": "31.4839", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Rakai", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Lwengo", 
      "lat": "-0.4161", 
      "lng": "31.4081", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Lwengo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bukwo", 
      "lat": "1.3000", 
      "lng": "34.7500", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Bukwa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kasanda", 
      "lat": "0.5567", 
      "lng": "31.8022", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Mubende", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dokolo", 
      "lat": "1.9167", 
      "lng": "33.1720", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Dokolo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kamwenge", 
      "lat": "0.2111", 
      "lng": "30.4208", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kamwenge", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ngora", 
      "lat": "1.4314", 
      "lng": "33.7772", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Ngora", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Alebtong", 
      "lat": "2.2447", 
      "lng": "33.2547", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Alebtong", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kanungu", 
      "lat": "-0.9575", 
      "lng": "29.7897", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kanungu", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kanoni", 
      "lat": "0.1772", 
      "lng": "31.8811", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Gomba", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Oyam", 
      "lat": "2.2141", 
      "lng": "32.3703", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Oyam", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sembabule", 
      "lat": "-0.0772", 
      "lng": "31.4567", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Sembabule", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kakumiro", 
      "lat": "0.7806", 
      "lng": "31.3236", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kibaale", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Buyende", 
      "lat": "1.1517", 
      "lng": "33.1550", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Buyende", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kalaki", 
      "lat": "1.8160", 
      "lng": "33.3370", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kaberamaido", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Isingiro", 
      "lat": "-0.8686", 
      "lng": "30.8302", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Isingiro", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kyegegwa", 
      "lat": "0.5022", 
      "lng": "31.0414", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kyegegwa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Butalangu", 
      "lat": "0.7011", 
      "lng": "32.2481", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nakaseke", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Amolatar", 
      "lat": "1.6378", 
      "lng": "32.8448", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Amolatar", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Lamwo", 
      "lat": "3.5297", 
      "lng": "32.8016", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Lamwo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Palenga", 
      "lat": "2.6131", 
      "lng": "32.3369", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Gulu", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kotido", 
      "lat": "2.9806", 
      "lng": "34.1331", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kotido", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Pader", 
      "lat": "3.0500", 
      "lng": "33.2167", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Pader", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Agago", 
      "lat": "2.8338", 
      "lng": "33.3336", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Agago", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bulisa", 
      "lat": "2.1178", 
      "lng": "31.4116", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Buliisa", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Amudat", 
      "lat": "1.9500", 
      "lng": "34.9500", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Amudat", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Nabilatuk", 
      "lat": "2.0525", 
      "lng": "34.5734", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nakapiripirit", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Napak", 
      "lat": "2.2514", 
      "lng": "34.2501", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Napak", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kiryandongo", 
      "lat": "1.8763", 
      "lng": "32.0622", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kiryandongo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kiruhura", 
      "lat": "-0.2356", 
      "lng": "30.8725", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kiruhura", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Abim", 
      "lat": "2.7017", 
      "lng": "33.6761", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Abim", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ntoroko", 
      "lat": "1.0411", 
      "lng": "30.4811", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Ntoroko", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Otuke", 
      "lat": "2.5004", 
      "lng": "33.5007", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Otuke", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Amuru", 
      "lat": "2.8139", 
      "lng": "31.9387", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Amuru", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Nakapiripirit", 
      "lat": "1.9167", 
      "lng": "34.7833", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nakapiripirit", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kyankwanzi", 
      "lat": "1.1987", 
      "lng": "31.8062", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Kyankwanzi", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Nwoya", 
      "lat": "2.6342", 
      "lng": "32.0011", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Nwoya", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kitamilo", 
      "lat": "0.2222", 
      "lng": "33.2061", 
      "country": "Uganda", 
      "iso2": "UG", 
      "admin_name": "Buvuma", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }
  ]
  